# Generated by Django 3.0.8 on 2021-03-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateTimeField(verbose_name='notice date')),
                ('check_view', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateTimeField(verbose_name='image date')),
                ('image', models.ImageField(upload_to='pictures')),
                ('species', models.IntegerField()),
            ],
        ),
    ]
